import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import { LoadingPanel } from "../components/common/LoadingPanel";
import { CustomSelect } from "../components/common/CustomSelect";
import { PageHeader } from "../components/common/PageHeader";
import { approvePost, listPosts, publishPostNow, rejectPost } from "../features/posts/api/postApi";
import type { PostStatus, SocialPost } from "../shared/types/posts";

const STATUS_OPTIONS: Array<{ value: PostStatus; label: string }> = [
  { value: "draft", label: "Draft" },
  { value: "approved", label: "Approved" },
  { value: "scheduled", label: "Scheduled" },
  { value: "published", label: "Published" },
  { value: "failed", label: "Failed" },
  { value: "rejected", label: "Rejected" },
];

export function PostsPage() {
  const navigate = useNavigate();
  const [posts, setPosts] = useState<SocialPost[]>([]);
  const [statusFilter, setStatusFilter] = useState<PostStatus | "">("");
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const loadPosts = async () => {
    setLoading(true);
    try {
      const response = await listPosts({ status: statusFilter });
      setPosts(response.items);
      setError(null);
    } catch (err: any) {
      setError(err.response?.data?.detail ?? "Unable to load posts.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPosts();
  }, [statusFilter]);

  const handleApprove = async (postId: number) => {
    await approvePost(postId);
    setMessage("Post approved.");
    await loadPosts();
  };

  const handleReject = async (postId: number) => {
    const reason = window.prompt("Enter rejection reason", "Needs revision");
    if (!reason) return;
    await rejectPost(postId, reason);
    setMessage("Post rejected.");
    await loadPosts();
  };

  const handlePublishNow = async (postId: number) => {
    await publishPostNow(postId);
    setMessage("Publish job queued.");
    await loadPosts();
  };

  return (
    <section>
      <PageHeader
        eyebrow="Posts"
        title="Facebook post automation"
        description="Manage drafts, approvals, schedules, and publish workflows for Facebook-ready content with future AI and media publishing support."
      />

      {message ? <div className="panel success-panel">{message}</div> : null}
      {error ? <div className="panel error-panel">{error}</div> : null}

      <div className="panel posts-toolbar">
        <label className="posts-status-filter">
          Status filter
          <CustomSelect
            className="posts-status-filter-select"
            value={statusFilter}
            onChange={(value) => setStatusFilter(value as PostStatus | "")}
            options={[{ value: "", label: "All statuses" }, ...STATUS_OPTIONS]}
          />
        </label>
        <button type="button" onClick={() => navigate("/posts/new")}>Create post</button>
      </div>

      <div className="table-card">
        <div className="table-card-header">
          <h3>Posts</h3>
          <span className="muted-copy small-copy">{posts.length} loaded</span>
        </div>
        {loading ? <LoadingPanel message="Loading posts..." hint="Reading draft, scheduled, and published content." compact /> : null}
        {!loading ? (
          <table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Status</th>
                <th>Generated by</th>
                <th>Schedule</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {posts.map((post) => (
                <tr key={post.id}>
                  <td>
                    <strong>{post.title || "Untitled post"}</strong>
                    <div className="muted-copy small-copy">{post.content.slice(0, 80)}{post.content.length > 80 ? "..." : ""}</div>
                  </td>
                  <td><span className={`status-pill post-status-${post.status}`}>{post.status}</span></td>
                  <td>{post.generated_by}{post.is_llm_generated ? " | AI" : ""}</td>
                  <td>{post.scheduled_for ? new Date(post.scheduled_for).toLocaleString() : "Not scheduled"}</td>
                  <td className="table-actions">
                    <Link className="link-button" to={`/posts/${post.id}`}>Edit</Link>
                    {post.status === "draft" || post.status === "rejected" ? (
                      <button type="button" className="link-button" onClick={() => handleApprove(post.id)}>
                        Approve
                      </button>
                    ) : null}
                    {post.status !== "published" ? (
                      <button type="button" className="link-button" onClick={() => handlePublishNow(post.id)}>
                        Publish now
                      </button>
                    ) : null}
                    {post.status !== "published" ? (
                      <button type="button" className="link-button danger-link" onClick={() => handleReject(post.id)}>
                        Reject
                      </button>
                    ) : null}
                  </td>
                </tr>
              ))}
              {posts.length === 0 ? (
                <tr>
                  <td colSpan={5}>No posts found.</td>
                </tr>
              ) : null}
            </tbody>
          </table>
        ) : null}
      </div>
    </section>
  );
}
